### ISSUE TITLE
[feat] Guide progress for users building a project

### ISSUE THREAD

**Issue by naikymen** [koalazak/stepwisedocs#1]
El caso es el de un usuario (o grupo de usuarios) siguiendo una guia, y marcando su avance en cada una, para saber donde "dejó" de trabajar al momento de retomar.

Es útil para un usuario porque sabe donde quedó después de un tiempo, y para otros usuarios, que quieran continuar el trabajo.

Esto requiere tener "instancias" de las "guias", que son las guias que los usuarios "ejecutan".

La UI podria mostrar a cada usuario el porcentaje de avance de las guias o proyectos que empezó en las pantallas principales.

En la UI podría haber:

1. boton de start: crea una "copia" de la guia en su ultima version, y se renderea esa copia con una URL unica en el browser.
2. en las copias se puede guardar el avance con checkboxes.
3. boton de reanudar: te lleva a la ultima copia que hiciste.
4. boton de "clear progress": quita todo el avance registrado.
6. boton de editar: te lleva a la URL principal de la guia que ya armaste.

Algunas preguntas:

- Que deberia pasar con una instancia cuando su guia "madre" es actualizada?
- Qué debería pasar con los comentarios en una instancia? Se muestran los públicos? Los privados? Todos?

![image](https://github.com/koalazak/stepwisedocs/assets/3259326/cce26fb4-40fa-4038-a89d-3d0f9866705b)

**Comment by koalazak** [comment]
done

**Comment by naikymen** [comment]
Como se usa?

**Comment by koalazak** [comment]
whatsapp
