### ISSUE TITLE
[bug] Draft show up in TOC of public guides

### ISSUE THREAD

**Issue by naikymen** [koalazak/stepwisedocs#11]
Drafts are not listed in guides list, but they still appear on the public guide's TOC:

![Screenshot_20240605_000616](https://github.com/koalazak/stepwisedocs/assets/3259326/b120ba6c-a970-4bbd-9def-5fa960df9af5)

![Screenshot_20240605_000624](https://github.com/koalazak/stepwisedocs/assets/3259326/10a403f8-7010-4848-98d7-78b13cc56644)

**Comment by koalazak** [comment]
fixed
