### ISSUE TITLE
[feat] Add  "yellow", and HEX-coded colors to bullet list

### ISSUE THREAD

**Issue by naikymen** [koalazak/stepwisedocs#8]
I really need yellow (?)
- [x] yellow
- [x] hex

**Comment by naikymen** [comment]
![image](https://github.com/koalazak/stepwisedocs/assets/3259326/c0288569-a28a-4d5b-bc69-c1c2a8fc6300)

**Comment by koalazak** [comment]
added yellow and removed custom bullets from OL

**Comment by koalazak** [comment]
added hex
